### ISSUE TITLE
getting an error: 	exceptions.KeyError: 'url'

### ISSUE THREAD

**Issue by javed1211** [knockrentals/scrapy-elasticsearch#13]
![screenshot from 2015-06-23 15 38 35](https://cloud.githubusercontent.com/assets/13015455/8303782/002367d4-19be-11e5-8ae1-5ef83aeee380.png)

**Comment by jayzeng** [comment]
@javed1211 url is the default key value and you can/should change it to something base on your user case. 

In your settings.py, update:
ELASTICSEARCH_UNIQ_KEY = 'your_unique_key_name'

**Comment by zbhr46** [comment]
Hi jayzeng, please could you explain the ELASTICSEARCH_UNIQ_KEY value and what it should be changed to for an example case. i've read on stackexchange that a possible solution is to create a field for the unique key value in the scraper, but i don't really understand what this means either.  i'm just running on localhost:9200 and it's not working when using the default value 'url'. i'm getting this error:

2015-08-05 16:42:59 [scrapy] ERROR: Error processing {'link': [u'http://www.meetup.com/Search-Meetup-Karlsruhe/events/192357732/'],
 'title': [u'Suchen in der vernetzten Welt']}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 70, in process_item
    self.index_item(item)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 52, in index_item
    local_id = hashlib.sha1(item[uniq_key]).hexdigest()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/item.py", line 56, in __getitem__
    return self._values[key]
KeyError: 'url'


any help would be greatly appreciated!

**Comment by jayzeng** [comment]
@zbhr46 it should be "link" in your case. The unique key should be a field declared in your Item (that extends scrapy.Item). For example, if you have a item model like:

```
class Post(scrapy.Item):
    title = scrapy.Field()
    link = scrapy.Field()
``` 

you have two fields here, title and link, where link guarantees uniqueness and we hash this value and use it as "id" when persists to elasticsearch. 

Let me know if you have any other question
