### ISSUE TITLE
 got an unexpected keyword argument 'headers'

### ISSUE THREAD

**Issue by llermaly** [knockrentals/scrapy-elasticsearch#79]
Hello, Im trying to insert data into Bonsai.io ES cloud and getting this error : 

  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 1155, in bulk
    headers={'content-type': 'application/x-ndjson'})
TypeError: perform_request() got an unexpected keyword argument 'headers'

How can I solve it? 

Thanks

**Comment by llermaly** [comment]
maybe related to this: https://www.elastic.co/es/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by jayzeng** [comment]
interesting, what version of ES were you on?

**Comment by daviwesley** [comment]
I'm experience the same error

Elastic version: 7.12.0
```
Traceback (most recent call last):
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\twisted\internet\defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\scrapy\utils\defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\scrapyelasticsearch\scrapyelasticsearch.py", line 153, in process_item
    self.index_item(item)
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\scrapyelasticsearch\scrapyelasticsearch.py", line 142, in index_item
    self.send_items()
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\scrapyelasticsearch\scrapyelasticsearch.py", line 146, in send_items
    helpers.bulk(self.es, self.items_buffer)
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\elasticsearch\helpers\actions.py", line 396, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\elasticsearch\helpers\actions.py", line 317, in streaming_bulk
    for data, (ok, info) in zip(
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\elasticsearch\helpers\actions.py", line 234, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\elasticsearch\client\utils.py", line 153, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "c:\users\davi\.virtualenvs\crawlertron-zaw_chy4\lib\site-packages\elasticsearch\client\__init__.py", line 455, in bulk
    return self.transport.perform_request(
TypeError: perform_request() got an unexpected keyword argument 'headers'
```
